# Generated by Django 3.2.8 on 2021-12-01 18:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=270, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('slug', models.SlugField()),
                ('details', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='events.tag')),
            ],
        ),
    ]
