# Generated by Django 3.2.10 on 2021-12-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_singleticket_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
