# Generated by Django 3.2.10 on 2021-12-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tickettype_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
