# Generated by Django 3.2.10 on 2021-12-09 01:30

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211208_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
