# Generated by Django 3.2.10 on 2021-12-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211212_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=270, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='singleticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Ticket Type', 'verbose_name_plural': 'Ticket Types'},
        ),
        migrations.AddField(
            model_name='tickettype',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='events.AddOn'),
        ),
    ]
