# Generated by Django 3.2.10 on 2021-12-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_addon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='sponsorship',
            field=models.BooleanField(default=False),
        ),
    ]
