# Generated by Django 3.2.10 on 2021-12-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('events', '0014_auto_20211212_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleticket',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingprofile'),
        ),
        migrations.AlterField(
            model_name='singleticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='singleticket',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.guest'),
        ),
        migrations.AlterField(
            model_name='singleticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=270),
        ),
    ]
