# Generated by Django 3.2.10 on 2021-12-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20211216_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleticket',
            name='guest_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
