# Generated by Django 3.2.10 on 2022-02-16 03:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_singleticket_guest_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
