# Generated by Django 3.2.10 on 2022-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20220216_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
