# Generated by Django 3.2.10 on 2022-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_tickettype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
