# Generated by Django 3.2.10 on 2022-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20220216_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='sale_description',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
