# Generated by Django 3.2.10 on 2022-02-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkout_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
