# Generated by Django 3.2.10 on 2022-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_checkout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='singleticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
