# Generated by Django 3.2.10 on 2022-03-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20220305_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_description',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
