# Generated by Django 3.2.10 on 2022-03-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_price_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='price_description',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
