# Generated by Django 3.2.10 on 2022-03-25 03:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_ad_adtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
