# Generated by Django 3.2.10 on 2022-03-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_adtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkout_img_link',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.adtype'),
        ),
    ]
