# Generated by Django 3.2.10 on 2022-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20220329_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleticket',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
