# Generated by Django 3.2.10 on 2022-03-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_singleticket_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
