# Generated by Django 3.2.10 on 2022-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_singleticket_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleticket',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
