# Generated by Django 3.2.10 on 2022-04-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_completedonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedonation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='completedonation',
            name='subscription_id',
        ),
    ]
