# Generated by Django 3.2.10 on 2022-05-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_artist_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
