# Generated by Django 3.2.10 on 2022-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_remove_galleryitem_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
