# Generated by Django 3.2.10 on 2022-05-07 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_galleryitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedonation',
            options={'verbose_name': 'Event Donation', 'verbose_name_plural': 'Event Donations'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['artist', 'price'], 'verbose_name': 'Juneteenth Pre-Sale Item', 'verbose_name_plural': 'Juneteenth Pre-Sale Items'},
        ),
        migrations.AddField(
            model_name='singleticket',
            name='checked_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.singleticket')),
            ],
        ),
    ]
