# Generated by Django 4.0.5 on 2022-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_ad_braintree_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['artist', 'price'], 'verbose_name': 'Juneteenth Art Show Item', 'verbose_name_plural': 'Juneteenth Art Show Items'},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='pre_sale',
            field=models.BooleanField(default=False),
        ),
    ]
