# Generated by Django 4.0.5 on 2022-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_fullgalleryitem_alter_galleryitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('artist', models.CharField(max_length=270)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('width', models.CharField(blank=True, max_length=20)),
                ('height', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
