# Generated by Django 3.2.10 on 2022-06-18 13:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_artist_bio_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='ticket',
        ),
        migrations.AddField(
            model_name='checkin',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='events.SingleTicket'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
