# Generated by Django 3.2.10 on 2022-06-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_auto_20220618_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='guest_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
