# Generated by Django 3.2.10 on 2022-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_checkin_guest_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='guests',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
