# Generated by Django 3.2.10 on 2022-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_checkin_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='first_name',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='last_name',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='guests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
