# Generated by Django 3.2.10 on 2022-06-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_auto_20220618_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-time']},
        ),
    ]
