# Generated by Django 3.2.10 on 2022-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_alter_checkin_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='has_gallery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery_photos',
            field=models.ManyToManyField(blank=True, to='events.PhotoGalleryItem'),
        ),
    ]
