# Generated by Django 3.2.10 on 2022-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_auto_20220707_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
