# Generated by Django 3.2.10 on 2022-09-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_checkin_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['event', 'order', 'price'], 'verbose_name': 'Ticket Type', 'verbose_name_plural': 'Ticket Types'},
        ),
        migrations.AddField(
            model_name='tickettype',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
