# Generated by Django 3.2.10 on 2022-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20220831_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
