# Generated by Django 3.2.10 on 2022-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_tickettype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullgalleryitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
