# Generated by Django 4.1.2 on 2023-01-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_tickettype_registration_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='registration_url',
            field=models.CharField(blank=True, max_length=370, null=True),
        ),
    ]
