# Generated by Django 4.1.2 on 2023-01-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_alter_tickettype_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkout_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='checkout_img_link_2',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
