# Generated by Django 4.1.2 on 2023-01-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_event_checkout_image_2_event_checkout_img_link_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsor_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
