# Generated by Django 4.1.2 on 2023-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_event_sponsor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=270)),
                ('first_name', models.CharField(blank=True, max_length=270, null=True)),
                ('last_name', models.CharField(blank=True, max_length=270, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(blank=True, max_length=270, null=True)),
                ('initials', models.CharField(blank=True, max_length=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
