# Generated by Django 4.1.2 on 2023-01-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='initials',
        ),
    ]
