# Generated by Django 4.1.2 on 2023-03-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_remove_signature_initials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adtype',
            options={'ordering': ['price'], 'verbose_name': 'Ad Type', 'verbose_name_plural': 'Ad Types'},
        ),
    ]
