# Generated by Django 4.1.2 on 2023-05-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0067_alter_adtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullgalleryitem',
            name='year',
            field=models.BigIntegerField(default=2022),
        ),
    ]
