# Generated by Django 4.1.2 on 2023-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_fullgalleryitem_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullgalleryitem',
            options={'ordering': ['artist', 'title'], 'verbose_name': 'Juneteenth Art Show Item', 'verbose_name_plural': 'Juneteenth Art Show Items'},
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
