# Generated by Django 4.1.2 on 2023-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_alter_fullgalleryitem_options_galleryitem_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullgalleryitem',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
