# Generated by Django 4.1.2 on 2023-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_fullgalleryitem_donated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedonation',
            options={'ordering': ['-created'], 'verbose_name': 'Event Donation', 'verbose_name_plural': 'Event Donations'},
        ),
        migrations.AddField(
            model_name='fullgalleryitem',
            name='note',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='note',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
