# Generated by Django 4.1.2 on 2023-06-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_alter_completedonation_options_fullgalleryitem_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullgalleryitem',
            options={'ordering': ['sold', 'artist', 'title'], 'verbose_name': 'Juneteenth Art Show Item', 'verbose_name_plural': 'Juneteenth Art Show Items'},
        ),
    ]
