# Generated by Django 4.1.2 on 2023-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_alter_fullgalleryitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkout_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
