# Generated by Django 4.1.2 on 2023-08-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_artist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='image',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='type',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='artist',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ArtGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('url_path', models.CharField(max_length=270)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('items', models.ManyToManyField(blank=True, to='events.galleryitem')),
            ],
        ),
    ]
