# Generated by Django 4.1.2 on 2023-08-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_remove_auctionitem_image_auctionitem_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artgallery',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
