# Generated by Django 4.1.2 on 2023-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_artgallery_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artgallery',
            name='url_path',
        ),
        migrations.AlterField(
            model_name='artgallery',
            name='items',
            field=models.ManyToManyField(blank=True, to='events.fullgalleryitem'),
        ),
    ]
