# Generated by Django 4.1.2 on 2023-08-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_remove_artgallery_url_path_alter_artgallery_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullgalleryitem',
            options={'ordering': ['-sold', 'artist', 'title'], 'verbose_name': 'Juneteenth Art Show Item', 'verbose_name_plural': 'Juneteenth Art Show Items'},
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='type',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='width',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='buy_now_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='minimum_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
