# Generated by Django 4.1.2 on 2023-08-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_alter_fullgalleryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='donor',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
