# Generated by Django 4.1.2 on 2023-08-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_auctionitem_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
