# Generated by Django 4.1.2 on 2023-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_alter_auctionitem_options_auctionitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='qty_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
