# Generated by Django 4.1.2 on 2023-09-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0084_tickettype_qty_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_tbd',
            field=models.BooleanField(default=False),
        ),
    ]
