# Generated by Django 4.1.2 on 2023-12-31 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_event_date_tbd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_event_title', models.CharField(blank=True, max_length=270, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('group', models.CharField(blank=True, max_length=270, null=True)),
                ('guest_list', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.guest')),
            ],
        ),
    ]
