# Generated by Django 4.1.2 on 2023-12-31 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0086_freeregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeregistration',
            name='custom_event_title',
        ),
        migrations.CreateModel(
            name='FreeRegistrationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_event_title', models.CharField(blank=True, max_length=270, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mailchimp_journey_id', models.CharField(blank=True, max_length=120, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
