# Generated by Django 4.1.2 on 2023-12-31 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_remove_freeregistration_custom_event_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeregistration',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.freeregistrationtemplate'),
        ),
    ]
