# Generated by Django 4.1.2 on 2024-01-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0088_alter_freeregistration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free_reg',
            field=models.BooleanField(default=False),
        ),
    ]
