# Generated by Django 4.1.2 on 2024-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0089_event_free_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeregistration',
            name='affiliation',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
