# Generated by Django 4.1.2 on 2024-01-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_freeregistration_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeregistration',
            name='end_date',
        ),
        migrations.AddField(
            model_name='freeregistrationtemplate',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
