# Generated by Django 4.1.2 on 2024-01-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_remove_freeregistration_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeregistrationtemplate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
