# Generated by Django 3.2.5 on 2021-08-11 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bingo_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=300)),
                ('spot1', models.CharField(max_length=500)),
                ('spot2', models.CharField(max_length=500)),
                ('spot3', models.CharField(max_length=500)),
                ('spot4', models.CharField(max_length=500)),
                ('spot5', models.CharField(max_length=500)),
                ('spot6', models.CharField(max_length=500)),
                ('spot7', models.CharField(max_length=500)),
                ('spot8', models.CharField(max_length=500)),
                ('spot9', models.CharField(max_length=500)),
                ('spot10', models.CharField(max_length=500)),
                ('spot11', models.CharField(max_length=500)),
                ('spot12', models.CharField(max_length=500)),
                ('spot14', models.CharField(max_length=500)),
                ('spot15', models.CharField(max_length=500)),
                ('spot16', models.CharField(max_length=500)),
                ('spot17', models.CharField(max_length=500)),
                ('spot18', models.CharField(max_length=500)),
                ('spot19', models.CharField(max_length=500)),
                ('spot20', models.CharField(max_length=500)),
                ('spot21', models.CharField(max_length=500)),
                ('spot22', models.CharField(max_length=500)),
                ('spot23', models.CharField(max_length=500)),
                ('spot24', models.CharField(max_length=500)),
                ('spot25', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user_bingo_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot1', models.BooleanField(default=False)),
                ('spot2', models.BooleanField(default=False)),
                ('spot3', models.BooleanField(default=False)),
                ('spot4', models.BooleanField(default=False)),
                ('spot5', models.BooleanField(default=False)),
                ('spot6', models.BooleanField(default=False)),
                ('spot7', models.BooleanField(default=False)),
                ('spot8', models.BooleanField(default=False)),
                ('spot9', models.BooleanField(default=False)),
                ('spot10', models.BooleanField(default=False)),
                ('spot11', models.BooleanField(default=False)),
                ('spot12', models.BooleanField(default=False)),
                ('spot14', models.BooleanField(default=False)),
                ('spot15', models.BooleanField(default=False)),
                ('spot16', models.BooleanField(default=False)),
                ('spot17', models.BooleanField(default=False)),
                ('spot18', models.BooleanField(default=False)),
                ('spot19', models.BooleanField(default=False)),
                ('spot20', models.BooleanField(default=False)),
                ('spot21', models.BooleanField(default=False)),
                ('spot22', models.BooleanField(default=False)),
                ('spot23', models.BooleanField(default=False)),
                ('spot24', models.BooleanField(default=False)),
                ('spot25', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
