# Generated by Django 3.2.5 on 2021-08-19 02:50

import bfchallenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo_card',
            name='spot10_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot11_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot12_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot14_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot15_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot16_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot17_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot18_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot19_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot1_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot20_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot21_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot22_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot23_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot24_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot25_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot2_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot3_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot4_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot5_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot6_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot7_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot8_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot9_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
    ]
