# Generated by Django 3.2.5 on 2021-08-19 03:13

import bfchallenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0002_auto_20210819_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingo_card',
            name='spot13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bingo_card',
            name='spot13_img',
            field=models.ImageField(blank=True, null=True, upload_to=bfchallenge.models.upload_image_path),
        ),
    ]
