# Generated by Django 3.2.6 on 2021-08-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0003_auto_20210819_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingo_card',
            options={'verbose_name': 'Bingo Card', 'verbose_name_plural': 'Bingo Cards'},
        ),
        migrations.AlterModelOptions(
            name='user_bingo_card',
            options={'verbose_name': 'User Bingo Card', 'verbose_name_plural': 'User Bingo Cards'},
        ),
    ]
