# Generated by Django 3.2.6 on 2021-09-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0009_everyfriday_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readysetshop_transaction',
            name='receipt',
        ),
        migrations.AddField(
            model_name='readysetshop_transaction',
            name='receipt_aws',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
