# Generated by Django 3.2.6 on 2021-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0011_auto_20210906_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bingo_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25')], max_length=20)),
                ('field1', models.CharField(max_length=300)),
                ('field2', models.CharField(blank=True, max_length=300, null=True)),
                ('field3', models.CharField(blank=True, max_length=300, null=True)),
                ('field4', models.CharField(blank=True, max_length=300, null=True)),
                ('field5', models.CharField(blank=True, max_length=300, null=True)),
                ('field6', models.CharField(blank=True, max_length=300, null=True)),
                ('field7', models.CharField(blank=True, max_length=300, null=True)),
                ('field8', models.CharField(blank=True, max_length=300, null=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
