# Generated by Django 3.2.6 on 2021-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0012_user_bingo_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bingo_form',
            name='spot',
            field=models.CharField(max_length=20),
        ),
    ]
