# Generated by Django 3.2.6 on 2021-09-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0013_alter_user_bingo_form_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bingo_form',
            name='card',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bfchallenge.user_bingo_card'),
            preserve_default=False,
        ),
    ]
