# Generated by Django 3.2.6 on 2021-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0014_user_bingo_form_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bingo_form',
            name='field10',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field11',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field12',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field13',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field14',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field15',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field16',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='field9',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
