# Generated by Django 3.2.7 on 2021-10-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0015_auto_20210908_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_bingo_form',
            options={'verbose_name': 'User Bingo Form', 'verbose_name_plural': 'User Bingo Forms'},
        ),
    ]
