# Generated by Django 3.2.8 on 2021-10-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0016_alter_user_bingo_form_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readysetshop_transaction',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
