# Generated by Django 3.2.8 on 2021-10-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210906_1939'),
        ('bfchallenge', '0017_alter_readysetshop_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='readysetshop_transaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team'),
        ),
    ]
