# Generated by Django 3.2.8 on 2021-10-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210906_1939'),
        ('bfchallenge', '0018_readysetshop_transaction_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='everyfriday_transaction',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team'),
        ),
        migrations.AddField(
            model_name='readysetshop_transaction',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spread_the_love_submission',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user_bingo_form',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
