# Generated by Django 3.2.8 on 2021-10-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0019_auto_20211014_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
