# Generated by Django 3.2.8 on 2021-10-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0021_nomination_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everyfriday_transaction',
            name='receipt_aws',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='readysetshop_transaction',
            name='receipt_aws',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_bingo_form',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
