# Generated by Django 3.2.8 on 2021-11-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfchallenge', '0022_auto_20211029_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='readysetshop_transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='readysetshop_transaction',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='readysetshop_transaction',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
