# Generated by Django 3.2.10 on 2022-05-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_disbursement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='noitfication',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='payload',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recieved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['recieved_at'], name='billing_dis_recieve_1c9e97_idx'),
        ),
    ]
