# Generated by Django 3.2.10 on 2022-05-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20220518_1630'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disbursement',
            name='billing_dis_recieve_1c9e97_idx',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='recieved_at',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_id',
            field=models.CharField(max_length=270, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='transactions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
