# Generated by Django 3.2.10 on 2022-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_braintreetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='braintreetransaction',
            name='item',
            field=models.CharField(default=None, max_length=270),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='braintreetransaction',
            name='purchaser',
            field=models.CharField(default=None, max_length=270),
            preserve_default=False,
        ),
    ]
