# Generated by Django 3.2.10 on 2022-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20220519_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement_id',
            field=models.CharField(max_length=270, null=True),
        ),
    ]
