# Generated by Django 3.2.10 on 2022-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_disbursement_disbursement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='braintreetransaction',
            name='braintree_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
