# Generated by Django 3.2.10 on 2022-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_braintreetransaction_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='amount',
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='disbursement_id',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
