# Generated by Django 3.2.10 on 2022-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20220519_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreetransaction',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
    ]
