# Generated by Django 3.2.10 on 2022-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20220519_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='transactions',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
