# Generated by Django 3.2.8 on 2021-11-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20211113_0059'),
        ('donors', '0002_auto_20211113_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='events',
            field=models.ManyToManyField(blank=True, to='donations.donation_event'),
        ),
    ]
