# Generated by Django 3.2.8 on 2021-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
