# Generated by Django 3.2.8 on 2021-11-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donor_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
