# Generated by Django 3.2.10 on 2022-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_completedonation'),
        ('donors', '0007_donor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='event_donations',
            field=models.ManyToManyField(blank=True, to='events.CompleteDonation'),
        ),
    ]
