# Generated by Django 3.2.10 on 2022-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_donor_event_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_level',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
