# Generated by Django 3.2.10 on 2022-04-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_alter_donor_donor_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-total', 'last_name'], 'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
    ]
