# Generated by Django 4.1.2 on 2023-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0002_walker_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, max_length=32, null=True)),
                ('file', models.ImageField(upload_to='')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
