# Generated by Django 4.1.2 on 2023-04-14 12:03

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0005_walker_donation_goal_walker_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
