# Generated by Django 4.1.2 on 2023-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0006_walker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='captain_first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='captain_last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
