# Generated by Django 4.1.2 on 2023-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0007_organization_captain_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='donation_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
