# Generated by Django 4.1.2 on 2023-04-19 11:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0012_walker_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkerdonation',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='walkerdonation',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='walkerdonation',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='walkerdonation',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='walkerdonation',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_id', models.CharField(blank=True, max_length=120)),
                ('complete', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('message', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='walkathon.organization')),
            ],
        ),
    ]
