# Generated by Django 4.1.2 on 2023-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0013_walkerdonation_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='organization',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
