# Generated by Django 4.1.2 on 2023-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0014_alter_sponsorship_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdonation',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='orgdonation',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='orgdonation',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orgdonation',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orgdonation',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orgdonation',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orgdonation',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='walkerdonation',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='walkerdonation',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
