# Generated by Django 4.1.2 on 2023-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0015_orgdonation_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgdonation',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='walkerdonation',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='WalkerPledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_id', models.CharField(blank=True, max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('walker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='walkathon.walker')),
            ],
        ),
    ]
