# Generated by Django 4.1.2 on 2023-05-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0017_alter_organization_slug_alter_organization_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='waiver_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
