# Generated by Django 4.1.2 on 2023-11-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0019_orgdonation_email_orgdonation_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
