# Generated by Django 4.1.2 on 2024-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkathon', '0023_orgdonation_displayed_walkerdonation_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='fivek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walker',
            name='shirt_size',
            field=models.CharField(default='', max_length=270),
            preserve_default=False,
        ),
    ]
