# Generated by Django 3.2.8 on 2021-11-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='county',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='online_only',
        ),
        migrations.AddField(
            model_name='nomination',
            name='concerns',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='employees',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='revenue',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='structure',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='years_in_business',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
