# Generated by Django 3.2.8 on 2021-11-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0002_auto_20211123_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='concerns',
            new_name='other1',
        ),
        migrations.AddField(
            model_name='nomination',
            name='other2',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='other3',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='priority1',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='priority2',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='priority3',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
