# Generated by Django 3.2.10 on 2022-03-24 17:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0003_auto_20211123_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=270)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Business Phone Number', max_length=31)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=270, null=True)),
                ('age_range', models.CharField(blank=True, max_length=270, null=True)),
                ('household_size', models.CharField(blank=True, max_length=270, null=True)),
                ('income', models.CharField(blank=True, max_length=270, null=True)),
                ('priority1', models.CharField(blank=True, max_length=270, null=True)),
                ('other1', models.CharField(blank=True, max_length=270, null=True)),
                ('priority2', models.CharField(blank=True, max_length=270, null=True)),
                ('other2', models.CharField(blank=True, max_length=270, null=True)),
                ('priority3', models.CharField(blank=True, max_length=270, null=True)),
                ('other3', models.CharField(blank=True, max_length=270, null=True)),
            ],
            options={
                'verbose_name': 'VEN Family Nomination',
                'verbose_name_plural': 'VEN Family Nominations',
            },
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name': 'VEN Business Nomination', 'verbose_name_plural': 'VEN Business Nominations'},
        ),
    ]
