# Generated by Django 3.2.10 on 2022-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0005_auto_20220411_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='counselor',
            field=models.CharField(blank=True, default='Unassigned', max_length=200, null=True),
        ),
    ]
