# Generated by Django 3.2.10 on 2022-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0006_alter_nomination_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='familynomination',
            name='ven_id',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='ven_id',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
