# Generated by Django 3.2.10 on 2022-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0008_auto_20220411_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familynomination',
            name='counselor',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Andrew Frazier', 'Andrew Frazier'), ('Michelle Harlan', 'Michelle Harlan')], default='Unassigned', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='counselor',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Andrew Frazier', 'Andrew Frazier'), ('Michelle Harlan', 'Michelle Harlan')], default='Unassigned', max_length=200, null=True),
        ),
    ]
