# Generated by Django 3.2.10 on 2022-04-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0009_auto_20220411_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='other1',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Priority #1'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='other2',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Priority #2'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='other3',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Priority #3'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='priority1',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Priority #1'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='priority2',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Priority #2'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='priority3',
            field=models.CharField(blank=True, max_length=270, null=True, verbose_name='Priority #3'),
        ),
    ]
