# Generated by Django 3.2.10 on 2022-04-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0010_auto_20220411_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
