# Generated by Django 4.1.2 on 2023-01-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0012_sponsor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='expo_vendor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Interested in being Expo Vendor'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='pitch_comp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Interested in Pitch Competition'),
        ),
    ]
