# Generated by Django 4.1.2 on 2023-06-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ven', '0013_nomination_expo_vendor_nomination_pitch_comp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familynomination',
            options={'ordering': ['-created'], 'verbose_name': 'VEN Family Nomination', 'verbose_name_plural': 'VEN Family Nominations'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'ordering': ['-created'], 'verbose_name': 'VEN Business Nomination', 'verbose_name_plural': 'VEN Business Nominations'},
        ),
    ]
