# Generated by Django 3.2.6 on 2021-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp',
            name='online_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vbp',
            name='business_name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
