# Generated by Django 3.2.6 on 2021-08-23 00:27

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0002_auto_20210822_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp',
            name='phone_formatted',
            field=phone_field.models.PhoneField(blank=True, help_text='Business Phone Number', max_length=31),
        ),
    ]
