# Generated by Django 3.2.6 on 2021-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0003_vbp_phone_formatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vbp',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vbp',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
