# Generated by Django 3.2.6 on 2021-08-27 02:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0005_auto_20210827_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vbp_mdd',
            new_name='vbp_md',
        ),
        migrations.AlterModelManagers(
            name='vbp',
            managers=[
                ('unapproved_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
