# Generated by Django 3.2.6 on 2021-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0007_auto_20210827_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_book',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
