# Generated by Django 3.2.6 on 2021-09-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0010_alter_vbp_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vbp',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ak',
            options={'verbose_name': 'Alaska Listing', 'verbose_name_plural': 'Alaska Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_al',
            options={'verbose_name': 'Alabama Listing', 'verbose_name_plural': 'Alabama Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ar',
            options={'verbose_name': 'Arkansas Listing', 'verbose_name_plural': 'Arkansas Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_az',
            options={'verbose_name': 'Arizona Listing', 'verbose_name_plural': 'Arizona Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_book',
            options={'verbose_name': 'VBP Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ca',
            options={'verbose_name': 'California Listing', 'verbose_name_plural': 'California Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_co',
            options={'verbose_name': 'Colorado Listing', 'verbose_name_plural': 'Colorado Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ct',
            options={'verbose_name': 'Connecticut Listing', 'verbose_name_plural': 'Connecticut Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_dc',
            options={'verbose_name': 'DC Listing', 'verbose_name_plural': 'DC Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_de',
            options={'verbose_name': 'Delaware Listing', 'verbose_name_plural': 'Delaware Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_fl',
            options={'verbose_name': 'Florida Listing', 'verbose_name_plural': 'Florida Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ga',
            options={'verbose_name': 'Georgia Listing', 'verbose_name_plural': 'Georgia Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_hi',
            options={'verbose_name': 'Hawaii Listing', 'verbose_name_plural': 'Hawaii Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ia',
            options={'verbose_name': 'Iowa Listing', 'verbose_name_plural': 'Iowa Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_id',
            options={'verbose_name': 'Idaho Listing', 'verbose_name_plural': 'Idaho Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_il',
            options={'verbose_name': 'Illinois Listing', 'verbose_name_plural': 'Illinois Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_in',
            options={'verbose_name': 'Indiana Listing', 'verbose_name_plural': 'Indiana Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ks',
            options={'verbose_name': 'Kansas Listing', 'verbose_name_plural': 'Kansas Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ky',
            options={'verbose_name': 'Kentucky Listing', 'verbose_name_plural': 'Kentucky Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_la',
            options={'verbose_name': 'Louisiana Listing', 'verbose_name_plural': 'Louisiana Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ma',
            options={'verbose_name': 'Massachusetts Listing', 'verbose_name_plural': 'Massachusetts Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_md',
            options={'verbose_name': 'Maryland Listing', 'verbose_name_plural': 'Maryland Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_me',
            options={'verbose_name': 'Maine Listing', 'verbose_name_plural': 'Maine Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_mi',
            options={'verbose_name': 'Michigan Listing', 'verbose_name_plural': 'Michigan Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_mn',
            options={'verbose_name': 'Minnesota Listing', 'verbose_name_plural': 'Minnesota Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_mo',
            options={'verbose_name': 'Missouri Listing', 'verbose_name_plural': 'Missouri Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ms',
            options={'verbose_name': 'Mississippi Listing', 'verbose_name_plural': 'Mississippi Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_mt',
            options={'verbose_name': 'Montana Listing', 'verbose_name_plural': 'Montana Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_nc',
            options={'verbose_name': 'North Carolina Listing', 'verbose_name_plural': 'North Carolina Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_nd',
            options={'verbose_name': 'North Dakota Listing', 'verbose_name_plural': 'North Dakota Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ne',
            options={'verbose_name': 'Nebraska Listing', 'verbose_name_plural': 'Nebraska Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_nh',
            options={'verbose_name': 'New Hampshire Listing', 'verbose_name_plural': 'New Hampshire Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_nj',
            options={'verbose_name': 'New Jersey Listing', 'verbose_name_plural': 'New Jersey Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_nm',
            options={'verbose_name': 'New Mexico Listing', 'verbose_name_plural': 'New Mexico Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_nv',
            options={'verbose_name': 'Nevada Listing', 'verbose_name_plural': 'Nevada Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ny',
            options={'verbose_name': 'New York Listing', 'verbose_name_plural': 'New York Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_oh',
            options={'verbose_name': 'Ohio Listing', 'verbose_name_plural': 'Ohio Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ok',
            options={'verbose_name': 'Oklahoma Listing', 'verbose_name_plural': 'Oklahoma Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_or',
            options={'verbose_name': 'Oregon Listing', 'verbose_name_plural': 'Oregon Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_pa',
            options={'verbose_name': 'Pennsylvania Listing', 'verbose_name_plural': 'Pennsylvania Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ri',
            options={'verbose_name': 'Rhode Island Listing', 'verbose_name_plural': 'Rhode Island Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_sc',
            options={'verbose_name': 'South Carolina Listing', 'verbose_name_plural': 'South Carolina Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_sd',
            options={'verbose_name': 'South Dakota Listing', 'verbose_name_plural': 'South Dakota Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_tn',
            options={'verbose_name': 'Tennessee Listing', 'verbose_name_plural': 'Tennessee Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_tx',
            options={'verbose_name': 'Texas Listing', 'verbose_name_plural': 'Texas Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_ut',
            options={'verbose_name': 'Utah Listing', 'verbose_name_plural': 'Utah Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_va',
            options={'verbose_name': 'Virginia Listing', 'verbose_name_plural': 'Virginia Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_vt',
            options={'verbose_name': 'Vermont Listing', 'verbose_name_plural': 'Vermont Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_wa',
            options={'verbose_name': 'Washington Listing', 'verbose_name_plural': 'Washington Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_wi',
            options={'verbose_name': 'Wisconsin Listing', 'verbose_name_plural': 'Wisconsin Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_wv',
            options={'verbose_name': 'West Virginia Listing', 'verbose_name_plural': 'West Virginia Listings'},
        ),
        migrations.AlterModelOptions(
            name='vbp_wy',
            options={'verbose_name': 'Wyoming Listing', 'verbose_name_plural': 'Wyoming Listings'},
        ),
    ]
