# Generated by Django 3.2.8 on 2021-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0011_auto_20210909_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbp_nj',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vbp_nj',
            name='online_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vbp_nj',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
