# Generated by Django 3.2.8 on 2021-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0012_auto_20211013_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbp_ct',
            name='online_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vbp_ct',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
