# Generated by Django 3.2.8 on 2021-11-22 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_myuser_donor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vbp', '0016_auto_20211112_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vbp',
            options={'verbose_name': 'VBP Listing', 'verbose_name_plural': 'VBP Listings'},
        ),
        migrations.RemoveField(
            model_name='vbp',
            name='phone_formatted',
        ),
        migrations.RemoveField(
            model_name='vbp',
            name='state',
        ),
        migrations.AddField(
            model_name='vbp',
            name='nominator_owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vbp',
            name='nominator_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vbp',
            name='owner_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vbp',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team'),
        ),
        migrations.AddField(
            model_name='vbp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vbp',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Business Phone Number', max_length=31, null=True),
        ),
    ]
