# Generated by Django 3.2.10 on 2022-03-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0018_auto_20220208_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_la',
            name='address',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
