# Generated by Django 3.2.10 on 2022-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0019_vbp_la_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_la',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
