# Generated by Django 3.2.10 on 2022-03-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0020_vbp_la_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbp_la',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
