# Generated by Django 3.2.10 on 2022-03-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0022_alter_vbp_la_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vbp_la',
            name='zip_code',
        ),
    ]
