# Generated by Django 3.2.10 on 2022-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0023_remove_vbp_la_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_sc',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='vbp_sc',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
