# Generated by Django 3.2.10 on 2022-03-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0024_auto_20220303_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbp_sc',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
