# Generated by Django 3.2.10 on 2022-03-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0026_auto_20220303_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_book',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
