# Generated by Django 3.2.10 on 2022-04-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0029_auto_20220305_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_book',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vbp_book',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
