# Generated by Django 3.2.10 on 2022-04-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0030_auto_20220404_1650'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vbp',
            managers=[
            ],
        ),
    ]
