# Generated by Django 3.2.10 on 2022-07-19 00:12

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0032_auto_20220415_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='mv_private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Business Phone Number', max_length=31)),
                ('category', models.CharField(blank=True, choices=[('beauty', 'Beauty & Personal Grooming'), ('books', 'Books & Publishing'), ('cars', 'Cars & Automotive'), ('child', "Childcare | Children's Services & Products"), ('cleaning', 'Cleaning'), ('clothing', 'Clothing & Fashion'), ('construction', 'Construction & Trades'), ('education', 'Education'), ('eldercare', 'Eldercare'), ('electronics', 'Electronics & Technology'), ('entertainment', 'Entertainment'), ('farming', 'Farming & Agriculture'), ('florists', 'Florists'), ('grocery', 'Grocery & Food Services'), ('health', 'Health & Wellness'), ('home', 'Home & Garden'), ('hotels', 'Hotels & Hospitality | Travel'), ('jewelry', 'Jewelry & Accessories'), ('legal', 'Legal & Financial Services'), ('lifestyle', 'Lifestyle'), ('marketing', 'Marketing & Advertising'), ('medical', 'Medical Services'), ('packaging', 'Packaging | Delivery | Shipping'), ('pets', 'Pets & Animal Care'), ('photography', 'Photography & Video'), ('professional', 'Professional Services'), ('real estate', 'Real Estate'), ('recreation', 'Recreation & Sports'), ('restaurants', 'Restaurants & Bars | Event Spaces'), ('security', 'Security Services'), ('transportation', 'Transportation & Trucking'), ('visual', 'Visual & Performing Arts | Culture'), ('other', 'Other')], max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': "Martha's Vineyard listing",
                'verbose_name_plural': "Martha's Vineyard listings",
                'ordering': ['category', 'city', 'business_name'],
            },
        ),
    ]
