# Generated by Django 3.2.10 on 2022-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0035_auto_20220807_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mv_private',
            options={'ordering': ['category', 'cat_ordering', 'city', 'business_name'], 'verbose_name': "Martha's Vineyard listing", 'verbose_name_plural': "Martha's Vineyard listings"},
        ),
        migrations.AddField(
            model_name='mv_private',
            name='cat_ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
