# Generated by Django 3.2.10 on 2022-10-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0036_auto_20220807_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbp_ca',
            name='business_name',
            field=models.CharField(max_length=270),
        ),
        migrations.AlterField(
            model_name='vbp_ca',
            name='subcategory',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='vbp_ca',
            name='website',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
