# Generated by Django 4.1.2 on 2022-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0037_auto_20221025_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_nj',
            name='group',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='vbp_nj',
            name='is_grouped',
            field=models.BooleanField(default=False),
        ),
    ]
