# Generated by Django 4.1.2 on 2022-12-14 16:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0039_gift_guide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift_guide',
            options={'ordering': ['category', 'state', 'city', 'business_name'], 'verbose_name': 'Gift Guide Listing', 'verbose_name_plural': 'Gift Guide Listings'},
        ),
        migrations.RemoveField(
            model_name='gift_guide',
            name='cat_ordering',
        ),
        migrations.RemoveField(
            model_name='gift_guide',
            name='group',
        ),
        migrations.RemoveField(
            model_name='gift_guide',
            name='is_grouped',
        ),
        migrations.AddField(
            model_name='gift_guide',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='gift_guide',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gift_guide',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
