# Generated by Django 4.1.2 on 2023-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0040_alter_gift_guide_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('county', 'County'), ('state', 'State')], max_length=120)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
