# Generated by Django 4.1.2 on 2023-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0042_individualbook_slug_individualbook_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbp_book',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
