# Generated by Django 4.1.2 on 2023-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbp', '0043_vbp_book_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbook',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
