# Generated by Django 3.2.10 on 2021-12-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_singleticket_guest_list'),
        ('carts', '0003_ticketitem_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
