# Generated by Django 3.2.10 on 2022-03-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_ad_adtype'),
        ('carts', '0006_ticketdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.ticketcart')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.adtype')),
            ],
        ),
    ]
