# Generated by Django 3.2.10 on 2022-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_ticketad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
