# Generated by Django 3.2.10 on 2022-05-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_galleryitem_sold'),
        ('carts', '0008_gallerycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycart',
            name='items',
            field=models.ManyToManyField(blank=True, to='events.GalleryItem'),
        ),
    ]
