# Generated by Django 4.0.5 on 2022-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_fullgalleryitem_alter_galleryitem_options'),
        ('carts', '0009_gallerycart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullGalleryCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nonce', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('items', models.ManyToManyField(blank=True, to='events.galleryitem')),
            ],
        ),
    ]
