# Generated by Django 4.0.5 on 2022-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_fullgalleryitem_alter_galleryitem_options'),
        ('carts', '0010_fullgallerycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullgallerycart',
            name='items',
            field=models.ManyToManyField(blank=True, to='events.fullgalleryitem'),
        ),
    ]
