# Generated by Django 3.2.10 on 2022-04-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardmodel_model_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='fields',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='list_display',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='list_filter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='ordering',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='search_fields',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
