# Generated by Django 3.2.10 on 2022-04-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220406_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardmodel',
            old_name='fields',
            new_name='list_fields',
        ),
    ]
