# Generated by Django 3.2.10 on 2022-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_fields_dashboardmodel_list_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='list_fields_JSON',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
