# Generated by Django 3.2.10 on 2022-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboardmodel_display_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='edit_fields',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
