# Generated by Django 3.2.10 on 2022-04-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220406_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='view_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
