# Generated by Django 3.2.5 on 2021-08-15 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210804_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team'),
        ),
    ]
