# Generated by Django 3.2.5 on 2021-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
