# Generated by Django 3.2.6 on 2021-08-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='donor',
            field=models.BooleanField(default=False),
        ),
    ]
