# Generated by Django 3.2.6 on 2021-08-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='challenge_access',
            field=models.CharField(blank=True, choices=[('bingo', 'Power Bingo'), ('rss', 'Ready, Set, Shop!')], max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
