# Generated by Django 3.2.6 on 2021-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_myuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bingo_sponsor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='rss_sponsor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
