# Generated by Django 3.2.6 on 2021-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210827_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='donor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
