# Generated by Django 3.2.8 on 2021-10-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210906_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='donor',
        ),
    ]
