# Generated by Django 3.2.8 on 2021-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211130_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
