# Generated by Django 3.2.8 on 2021-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20211113_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation_event',
            options={'verbose_name': 'Event Category', 'verbose_name_plural': 'Event Categories'},
        ),
        migrations.RemoveField(
            model_name='donation_event',
            name='tags',
        ),
        migrations.AddField(
            model_name='donation',
            name='tags',
            field=models.ManyToManyField(blank=True, to='donations.tag'),
        ),
    ]
