# Generated by Django 3.2.8 on 2021-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20211113_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation_event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='donation_event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='donations.tag'),
        ),
    ]
