# Generated by Django 3.2.10 on 2022-04-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20211113_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
    ]
