# Generated by Django 3.2.10 on 2022-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_donation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-updated'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time'),
        ),
    ]
