# Generated by Django 3.2.8 on 2021-10-31 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('image_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('order_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order_by'],
            },
        ),
        migrations.CreateModel(
            name='newInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=270, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'Inventory',
                'ordering': ['sku', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandise.color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merchandise.size')),
            ],
        ),
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('card_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('shipping_weight', models.IntegerField(blank=True, null=True)),
                ('sale_active', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('images', models.ManyToManyField(to='merchandise.image')),
                ('inventory', models.ManyToManyField(through='merchandise.newInventory', to='merchandise.Variation')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='newinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.newproduct'),
        ),
        migrations.AddField(
            model_name='newinventory',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.variation'),
        ),
    ]
