# Generated by Django 4.1.2 on 2023-11-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_cloudflareimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='merchandise.image'),
        ),
    ]
