# Generated by Django 4.1.2 on 2023-11-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0005_alter_newproduct_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='images',
            field=models.ManyToManyField(blank=True, to='merchandise.cloudflareimage'),
        ),
    ]
