# Generated by Django 4.1.2 on 2023-11-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0007_newproduct_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproduct',
            options={'ordering': ['display_order', 'price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='card_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
