# Generated by Django 3.2.10 on 2021-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20211222_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbpscraped',
            name='phone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
