# Generated by Django 3.2.10 on 2021-12-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_vbpscraped_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbpscraped',
            name='city',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='vbpscraped',
            name='county',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='vbpscraped',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
