# Generated by Django 3.2.10 on 2021-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20211222_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbpscraped',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
