# Generated by Django 4.1.2 on 2023-09-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
