# Generated by Django 4.1.2 on 2023-10-02 02:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_flyer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageStriversApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('school_classification', models.CharField(blank=True, max_length=120, null=True)),
                ('interest', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('open_to_unpaid', models.CharField(blank=True, max_length=120, null=True, verbose_name='Open to unpaid internships/apprenticeships')),
            ],
        ),
        migrations.AlterModelOptions(
            name='flyer',
            options={'ordering': ['order', 'state']},
        ),
    ]
