# Generated by Django 4.1.2 on 2023-10-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_villagestriversapplication_alter_flyer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagestriversapplication',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
