# Generated by Django 4.1.2 on 2024-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_villagestriversapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyer',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
