# Generated by Django 4.1.2 on 2024-04-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_alter_flyer_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='pg2_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
