# Generated by Django 4.1.2 on 2024-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_flyer_pg2_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='clickable_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
