# Generated by Django 3.2.10 on 2022-02-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vbpus_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'VBP Cover',
                'verbose_name_plural': 'VBP Covers',
            },
        ),
        migrations.CreateModel(
            name='vbpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_source', models.CharField(blank=True, max_length=200, null=True)),
                ('business_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=50, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Business Phone Number', max_length=31, null=True)),
                ('category', models.CharField(blank=True, choices=[('beauty', 'Beauty & Personal Grooming'), ('books', 'Books & Publishing'), ('cars', 'Cars & Automotive'), ('child', "Childcare | Children's Services & Products"), ('cleaning', 'Cleaning'), ('clothing', 'Clothing & Fashion'), ('construction', 'Construction & Trades'), ('education', 'Education'), ('eldercare', 'Eldercare'), ('electronics', 'Electronics & Technology'), ('entertainment', 'Entertainment'), ('farming', 'Farming & Agriculture'), ('florists', 'Florists'), ('grocery', 'Grocery & Food Services'), ('health', 'Health & Wellness'), ('home', 'Home & Garden'), ('hotels', 'Hotels & Hospitality | Travel'), ('jewelry', 'Jewelry & Accessories'), ('legal', 'Legal & Financial Services'), ('lifestyle', 'Lifestyle'), ('marketing', 'Marketing & Advertising'), ('medical', 'Medical Services'), ('packaging', 'Packaging | Delivery | Shipping'), ('pets', 'Pets & Animal Care'), ('photography', 'Photography & Video'), ('professional', 'Professional Services'), ('real estate', 'Real Estate'), ('recreation', 'Recreation & Sports'), ('restaurants', 'Restaurants & Bars | Event Spaces'), ('security', 'Security Services'), ('transportation', 'Transportation & Trucking'), ('visual', 'Visual & Performing Arts | Culture'), ('other', 'Other')], max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('online_only', models.BooleanField(default=False)),
                ('nominator_name', models.CharField(blank=True, max_length=300, null=True)),
                ('nominator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nominator_owner', models.BooleanField(blank=True, default=False, null=True)),
                ('nominator_recommended', models.BooleanField(blank=True, default=False, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VBP Listing',
                'verbose_name_plural': 'VBP Listings',
            },
        ),
    ]
