# Generated by Django 3.2.6 on 2021-08-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_submission',
            options={'verbose_name': 'Contact Us Request', 'verbose_name_plural': 'Contact Us Requests'},
        ),
    ]
