# Generated by Django 3.2.10 on 2022-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contact_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_submission',
            name='received',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
