# Generated by Django 3.2.10 on 2022-04-20 02:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contact_submission_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'News Page Content',
                'verbose_name_plural': 'News Page Content',
            },
        ),
    ]
