# Generated by Django 3.2.8 on 2021-10-31 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('carts', '0001_initial'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('braintree_id', models.CharField(blank=True, max_length=270, null=True, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=270)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorization_expired', 'Authorization Expired'), ('authorized', 'Authorized'), ('authorizing', 'Authorizing'), ('settlement_pending', 'Settlement Pending'), ('settlement_declined', 'Settlement Declined'), ('failed', 'Failed'), ('gateway_rejected', 'Gateway Rejected'), ('processor_declined', 'Processor Declined'), ('settled', 'Settled'), ('settling', 'Settling'), ('submitted_for_settlement', 'Submitted For Settlement'), ('voided', 'Voided'), ('fulfilled', 'Fulfilled')], default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('device_data', models.CharField(blank=True, max_length=270, null=True)),
                ('shippo_obj', models.CharField(blank=True, max_length=270, null=True, verbose_name='Shippo ID')),
                ('label', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Shipping Label')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='addresses.address')),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingprofile')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.cart')),
                ('items', models.ManyToManyField(blank=True, to='carts.cartItem')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='addresses.address')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorization_expired', 'Authorization Expired'), ('authorized', 'Authorized'), ('authorizing', 'Authorizing'), ('settlement_pending', 'Settlement Pending'), ('settlement_declined', 'Settlement Declined'), ('failed', 'Failed'), ('gateway_rejected', 'Gateway Rejected'), ('processor_declined', 'Processor Declined'), ('settled', 'Settled'), ('settling', 'Settling'), ('submitted_for_settlement', 'Submitted For Settlement'), ('voided', 'Voided')], default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingprofile')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carts.cart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
