# Generated by Django 3.2.10 on 2022-05-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('events', '0042_galleryitem_order'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOAPresalePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_id', models.CharField(blank=True, max_length=270, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('billing_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingprofile')),
                ('items', models.ManyToManyField(blank=True, to='events.GalleryItem')),
            ],
            options={
                'verbose_name': 'Juneteenth Art Show Pre-Sale Order',
                'verbose_name_plural': 'Juneteenth Art Show Pre-Sale Orders',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
