# Generated by Django 3.2.10 on 2022-05-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_loapresalepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loapresalepurchase',
            name='billing_profile',
        ),
        migrations.AddField(
            model_name='loapresalepurchase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loapresalepurchase',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loapresalepurchase',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
