# Generated by Django 4.0.5 on 2022-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220519_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='loapresalepurchase',
            name='pickup_window',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
