# Generated by Django 4.0.5 on 2022-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_fullgalleryitem_alter_galleryitem_options'),
        ('orders', '0006_loapresalepurchase_pickup_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOAArtPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_id', models.CharField(blank=True, max_length=270, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('pickup_window', models.CharField(blank=True, max_length=270, null=True)),
                ('items', models.ManyToManyField(blank=True, to='events.fullgalleryitem')),
            ],
            options={
                'verbose_name': 'Juneteenth Art Purchase',
                'verbose_name_plural': 'Juneteenth Art Purchase',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
