# Generated by Django 4.0.5 on 2022-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_loaartpurchase_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaartpurchase',
            name='pickup_window',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
