# Generated by Django 3.2.10 on 2022-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_loaartpurchase_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_address_city',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_address_line_1',
            field=models.CharField(blank=True, max_length=370, null=True),
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_address_name',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_address_state',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_address_zip',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
