# Generated by Django 3.2.10 on 2022-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20221028_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaartpurchase',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loaartpurchase',
            name='shipping_requested',
            field=models.BooleanField(default=False),
        ),
    ]
