# Generated by Django 4.1.2 on 2023-08-19 01:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_auctionitem_donor'),
        ('orders', '0012_auto_20221028_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilentAuctionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorization_expired', 'Authorization Expired'), ('authorized', 'Authorized'), ('authorizing', 'Authorizing'), ('settlement_pending', 'Settlement Pending'), ('settlement_declined', 'Settlement Declined'), ('failed', 'Failed'), ('gateway_rejected', 'Gateway Rejected'), ('processor_declined', 'Processor Declined'), ('settled', 'Settled'), ('settling', 'Settling'), ('submitted_for_settlement', 'Submitted For Settlement'), ('voided', 'Voided'), ('fulfilled', 'Fulfilled')], default='created', max_length=120)),
                ('braintree_id', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.auctionitem')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
