# Generated by Django 4.1.2 on 2023-11-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_silentauctionpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippo_obj',
        ),
    ]
